### ISSUE TITLE
Metatags - Edge case: text encoding for quote

### ISSUE THREAD

**Issue by pablobarrera** [steven-tey/dub#426] opened 2023-10-24 15:23 UTC
Hi, I have been testing the metatags api to generate link previews and I found this edge case:

**Text encoding problem when there's a quote (") in the description (happens only on some links):**
Link: https://www.linkedin.com/posts/arielbenedetti_creatividad-ugcPost-7121195984461647872-r0zC?utm_source=share&utm_medium=member_desktop

Metatags shows `&quot;`:
<img width="522" alt="Screen Shot 2023-10-24 at 11 48 21" src="https://github.com/steven-tey/dub/assets/16086326/58d870f8-22db-4e63-9729-d6d03f1cd74f">

LinkPreview.net shows `"` properly:
<img width="1084" alt="Screen Shot 2023-10-24 at 11 49 10" src="https://github.com/steven-tey/dub/assets/16086326/10558963-1d0c-449a-b7e4-d16409256d3d">

**Comment by VishalMCF** [comment] 2023-11-04 11:45
Hi, I would like to try to tackle this issue. I have done my exploration. I don't need this to be assigned to me.

**Comment by steven-tey** [comment] 2023-11-04 15:18
@VishalMCF feel free to PR!

**Comment by VishalMCF** [comment] 2023-11-04 17:11
@steven-tey I am trying to setup the codebase. But the problem is that I am confused what does it mean to set up ngrok_url. There is little clarity on that part. Can you suggest what is referring to?
Does it mean that I have to create a ngrok domain??
I went through the documentation of ngrok and it is basically used for exposing your localhost application to the Internet for listening webhooks etc.
for that, there are two commands that needs to be run-> 
ngrok config add-authtoken <TOKEN>
ngrok http http://localhost:8080

Can someone please clarify it? I can raise a pull for documenting it so that in future other can also not get blocked

**Comment by VishalMCF** [comment] 2023-11-05 11:26
I got it. I referred to the code directly and it is asking me to create a custom domain if it is not a production environment.

**Closed** 2023-12-05 19:39 UTC
