### ISSUE TITLE
Bug: Unexpected Padding added to the bottom of Create/Edit Link Dialog

### ISSUE THREAD

**Issue by prathameshjchavan** [steven-tey/dub#338] opened 2023-08-27 06:39 UTC
Whenever the user tries to upload an image in the Create/Edit Link Dialog, there is some unexpected padding added to the bottom of the Dialog making the top section of the dialog unreachable and inconsistent UI.

Steps to Reproduce: 
1. Go to https://app.dub.co
2. Sign in to go to Dashboard
3. Click on 'Dub.sh Links'
4. Click on 'Create Link'
5. Toggle on 'Custom Social Media Cards'
6. Click on the section to upload an image 

https://github.com/steven-tey/dub/assets/74180320/eeb3c25a-db66-4ace-9800-d0ae5f72a271

**Comment by prathameshjchavan** [comment] 2023-08-28 12:06
I trying to solve this bug. But, I'm facing issues setting up the project locally.

I couldn't find any way to login to the dashboard. And there is no setup guide on this repo.

If anyone could help/guide me setup the project locally, the I could work on this issue.

Thanks!

**Comment by steven-tey** [comment] 2023-08-30 03:47
Seems related to #334!

re: local setup – were you able to add all the required env vars in `.env.example`?

**Comment by prathameshjchavan** [comment] 2023-08-30 07:00
> Seems related to #334!
> 
> re: local setup – were you able to add all the required env vars in `.env.example`?

Yes, I've added all the required envs.

But, I'm unable to register as a user. See this video:


https://github.com/steven-tey/dub/assets/74180320/c2160c8b-4c52-48c0-8433-f8cf02aeafb2

**Comment by VishnuVVR-369** [comment] 2023-09-10 10:05
@prathameshjchavan, May I know which node version you are using?

**Comment by prathameshjchavan** [comment] 2023-09-11 03:59
> @prathameshjchavan, May I know which node version you are using?

Node v18.17.1

**Comment by thevinitgupta** [comment] 2023-09-17 18:26
Can I work on this issue?
This might be because of some extra empty element being added.

**Comment by prathameshjchavan** [comment] 2023-09-18 02:45
> Can I work on this issue?
> This might be because of some extra empty element being added.

Have you got logged in to the dashboard in local environment?

**Comment by steven-tey** [comment] 2023-09-18 03:32
BTW just realized that this is reproducible on the homepage demo as well: https://github.com/steven-tey/dub/tree/main/app/ui/modals/add-edit-link-modal

That one doesn't require login I believe:
1. Clone the repo
2. Run `yarn dev`
3. Go to http://home.localhost:8888/
4. Click on the 3 dots to open up the link edit modal 
5. Toggle the custom social cards section and click upload button

<img width="1506" alt="CleanShot 2023-09-17 at 20 31 51@2x" src="https://github.com/steven-tey/dub/assets/28986134/7312592f-4e15-40c0-9134-b54c4075d99a">

**Comment by thevinitgupta** [comment] 2023-09-20 10:21
Hi Steven, I am not able to setup the project and get it running, could you assign this to someone else.
Thanks

**Comment by prathameshjchavan** [comment] 2023-09-22 06:22
> BTW just realized that this is reproducible on the homepage demo as well: https://github.com/steven-tey/dub/tree/main/app/ui/modals/add-edit-link-modal
> 
> That one doesn't require login I believe:
> 
> 1. Clone the repo
> 2. Run `yarn dev`
> 3. Go to http://home.localhost:8888/
> 4. Click on the 3 dots to open up the link edit modal
> 5. Toggle the custom social cards section and click upload button
> 
> <img alt="CleanShot 2023-09-17 at 20 31 51@2x" width="1506" src="https://user-images.githubusercontent.com/28986134/268550716-7312592f-4e15-40c0-9134-b54c4075d99a.png">

Thanks Steven, working on it!

**Comment by mhessdev** [comment] 2023-09-22 13:29
I just got it to happen as well. It was when switching the OG image. 
![image](https://github.com/steven-tey/dub/assets/36578389/0208d5d7-abcb-443e-a21e-59b95bc6d4ad)

If I get some time, ill see if I can lend a hand fixing it. Not a huge deal.

**Closed** 2023-09-24 03:47 UTC
