### ISSUE TITLE
Analytics Page not working

### ISSUE THREAD

**Issue by max-programming** [steven-tey/dub#114] opened 2022-11-11 13:30 UTC
For some reason, these analytics pages of mine do not work

1. https://app.dub.sh/links/steps-exp-ts
2. https://app.dub.sh/links/repo-exp-ts

![image](https://user-images.githubusercontent.com/51731966/201350353-37ed45cf-2d31-4f83-a285-ab862113d646.png)

**Comment by max-programming** [comment] 2022-11-11 13:32
`app.dub.sh/links/[slug]` does not show analytics.
But `dub.sh/stats/[slug]` does show properly

**Comment by steven-tey** [comment] 2022-11-11 22:58
This is due to a regression in Next.js 13: https://github.com/vercel/next.js/issues/42463

It should be fixed very soon but in the meantime, you can click on the link via https://app.dub.sh/links and it should work – just don't refresh it (refreshing the page breaks it somehow)

**Comment by steven-tey** [comment] 2022-11-14 00:06
Fixed this with a patched version of Next.js thanks to @ijjk – will upgrade to the canary version when it's published! :)

**Closed by steven-tey** 2022-11-14 00:06 UTC
