### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by sxadxsx** [steven-tey/dub#432] opened 2023-10-28 05:42 UTC
I try to deploy dub to vercel and I get this error,how to fix?
`dub-web:build: > Build error occurred
dub-web:build: Error: Failed to collect page data for /[domain]
dub-web:build:     at /vercel/path0/node_modules/.pnpm/next@13.5.5-canary.16_@babel+core@7.17.8_@opentelemetry+api@1.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1171:15 {
dub-web:build:   type: 'Error'`

**Comment by steven-tey** [comment] 2023-11-09 01:34
Closing this as a duplicate of #12

**Closed by steven-tey** 2023-11-09 01:34 UTC
