### ISSUE TITLE
Error while deploying to vercel : [ { code: 89, message: 'Invalid or expired token.' } ]

### ISSUE THREAD

**Issue by p0we7** [steven-tey/dub#232] opened 2023-06-07 09:07 UTC
I can't find any useful solutions on GitHub or the official website. 
Is there any way to solve this problem?

![SCR-20230607-ozzf](https://github.com/steven-tey/dub/assets/8407573/a59f3d10-df2a-4bfe-bf2a-c3f64eaa650a)

**Comment by steven-tey** [comment] 2023-06-08 00:18
This is because of the Static Tweet implementation on dub.sh and dub.sh/metatags, which requires a valid Twitter Auth Token. You can remove all instances of TWITTER_AUTH_TOKEN since that's just used to render the static tweets on the landing page.

Closing this since it's a duplicate of #12

**Closed by steven-tey** 2023-06-08 00:18 UTC
